name: dataanalysis
channels:
  - defaults
  - r
dependencies:
  - colorama
  - gitdb
  - gitpython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyyaml
  - r-cairo
  - r-caret
  - r-e1071
  - r-feather
  - r-irkernel
  - r-recommended
  - r-tidyverse
  - scipy
  - scikit-learn
  - seaborn
  - six
  - smmap
  - sphinx
  - sphinx_rtd_theme
  - sqlalchemy
  - pip:
    - https://github.com/coderefinery/sphinx-lesson/archive/master.zip
