---
title: An R Markdown document converted from "07_Bringing_It_Home.ipynb"
output: html_document
---

# Bringing it home

In this course we have seen, that a typical data science workflow goes as follows:

    1. We obtain a dataset
    2. We read in the dataset
    3. We modify the dataset into a tidy format
    4. Go through steps 1-3 and join data to your dataset until you have obtained all datasets you require
    5. We create a model based on the variables that we have with some variables acting as responses and others as predictors
    6. We run the model on our data
    7. We try to see how well the model fits
    8. Go through steps 5-7 until you have a working model
    9. We visualize the results

Let's try this in action.

# Exercise

It is often said that increase in life expectancy will reduce the amount of children people have as the probability of the child living into adulthood will be higher.

There's two files in `/m/jhnas/jupyter/shareddata/python-r-data-analysis/world-bank-data-1960-to-2016`:
    
    - `fertility_rate.csv` contains fertility rate data.
    - `life_expectancy.csv` constains life expectancy data.

There's one file in `/m/jhnas/jupyter/shareddata/python-r-data-analysis/world-capitals-gps`:

    - `concap.csv` contains GPS locations of world's capitals (and their country codes and continent codes).

Do the following:

1. Read these datasets in and make them into tidy format.

2. Use join-functions from `tidyverse` to join the important variables of these datasets together [[join]](https://dplyr.tidyverse.org/reference/join.html).

3. Calculate mean values and variations of fertility and life expectancy on a global and continental scale.

4. Fit linear model of life expectancy vs. fertility to each country. See which countries match the best and which do the worst.

5. Fit linear model of year vs life expectancy to each country. See which countries have done the most to improve on life expectancy since 1960.

```{r}
library(tidyverse)
if (!file.exists('rlibs')) {
    dir.create('rlibs')
}
if (!file.exists('rlibs/broom')) {
    install.packages('broom', repos="http://cran.r-project.org", lib='rlibs')
}
library(broom, lib.loc='rlibs')
library(modelr)
```

